### ISSUE TITLE
Tests fail when port 9998 or 9999 is in use

### ISSUE THREAD

**Issue by andk** [benkasminbullock/json-server#1]
Due to the hard coded port number 9998 in https://metacpan.org/release/BKB/JSON-Server-0.02/source/t/boolean.t#L8 , and 9999 in https://metacpan.org/release/BKB/JSON-Server-0.02/source/t/00-json-server.t#L14 the tests may fail. I found on my smoker the ports occupied by some other program:

```
tcp        0      0 0.0.0.0:9998            0.0.0.0:*               LISTEN      1005       2462604    4845/run.pl         
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      1005       2462623    4852/run.pl
```
After I killed these programs, the test passes.

Some test writers use for such cases Test::TCP to pick unused ports. Maybe this would make sense here too?

**Comment by benkasminbullock** [comment]
I made a new version & the tests look OK, so I'm going to release the new one to CPAN and I'll mark this closed for the time being, but if it does reoccur please reopen.

http://matrix.cpantesters.org/?dist=JSON-Server+0.02_01
